"""Update fields

Revision ID: bd088a927323
Revises: 6bde080afaed
Create Date: 2022-08-31 14:53:36.848501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd088a927323'
down_revision = '6bde080afaed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('urgency', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('tasks', sa.Column('importance', sa.Boolean(), server_default='FALSE', nullable=False))
    op.drop_column('tasks', 'important')
    op.drop_column('tasks', 'urgent')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='FALSE', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.add_column('tasks', sa.Column('urgent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('important', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'importance')
    op.drop_column('tasks', 'urgency')
    # ### end Alembic commands ###
